### ISSUE TITLE
[Question] Is there a way to run the features in parallel using CLI

### ISSUE THREAD

**Issue by hemanth-dunzo** [grasshopper7/cuke4parallel#1]
Is there a way to run the features in parallel using CLI

When we provide --threads=3 it runs the scenarios in parallel

Is there a way to run tags or features in parallel using the CLI

**Comment by grasshopper7** [comment]
@hemanth-dunzo Tags there is no option. If u use a junit runner it will run features in parallel. Check this out -> http://grasshopper.tech/464/
