### ISSUE TITLE
Issue to run the features or scenarios  in parallel using CLI

### ISSUE THREAD

**Issue by Ashwini-Devi** [grasshopper7/cuke4parallel#2]
Im utilizing the CLI but failing run the scenarios or features in parallel .Though it opens all four browser at a time it executes only focused browser on desktop so running only one feature and rest of the features .Kindly suggest me better option.

**Comment by grasshopper7** [comment]
Is your webdriver static? It will always run the features in the last browser opened. If you have a repository i can have a look. Refer to this for parallel running with selenium and cucumber > http://grasshopper.tech/732/
